version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
